### PR TITLE
Flip chevron for tab groups

### PR DESCRIPTION
**Pull request by Blackbaud-MattGregg**
Original modern theme creation for section tab included switching chevron direction for expand/collapse to follow accordion convention used elsewhere in system (repeaters, default styles vertical tabs groups). It was included in reverse. This PR switches chevron to point down (collapsed) and point up (expanded)

### CODE REVIEW

**Review by Blackbaud-AdamFunderburk — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-Fix-vertical-tab-chevron-direction](https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-Fix-vertical-tab-chevron-direction)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-Fix-vertical-tab-chevron-direction](https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-Fix-vertical-tab-chevron-direction)

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-MattGregg @Blackbaud-AdamFunderburk - as we move to the monorepo I'm going to close this PR. Let us know if this is still needed and we'll need to get a PR up there.

**Comment by Blackbaud-AdamFunderburk** [comment]
I think this will need a new PR, since this fix still needs to be made. Chevrons are backwards on modern vertical tab groups.
image

**Pull request closed without merging**
