### PR TITLE
Release 4.2.0

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**

### CODE REVIEW

**Comment by Blackbaud-TrevorBurch** [comment]
@michael-tims

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-tabs?_sp.spa=pr-release-4.2.0](https://host.nxt.blackbaud.com/skyux-tabs?_sp.spa=pr-release-4.2.0)

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-tabs?_sp.spa=pr-release-4.2.0](https://host.nxt.blackbaud.com/skyux-tabs?_sp.spa=pr-release-4.2.0)

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-DeniseCisneros date has been fixed

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-tabs?_sp.spa=pr-release-4.2.0](https://host.nxt.blackbaud.com/skyux-tabs?_sp.spa=pr-release-4.2.0)

**Pull request merged**
