### PR TITLE
Update sectioned form behavior demo to be in line with code example and to properly handle error states

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form](https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form](https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form](https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form)

**Review by Blackbaud-AlexKingman — DISMISSED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form](https://developer.blackbaud.com/skyux-tabs?_sp.spa=pr-demo-update-sectioned-form)

**Review by Blackbaud-AdamFunderburk — APPROVED** [review]

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Pull request merged**
